DNS_KEY_NOT_CHECKED = 0b000
DNS_KEY_KNOWN = 0b001
DNS_KEY_PUBLISHED = 0b010
DNS_KEY_DATA_OK = 0b100

DNS_KEY_KNOWN_AND_PUBLISHED = DNS_KEY_KNOWN | DNS_KEY_PUBLISHED
DNS_KEY_UNPUBLISHED = 1
DNS_KEY_UNKNOWN = 2
DNS_KEY_OK = DNS_KEY_KNOWN | DNS_KEY_PUBLISHED | DNS_KEY_DATA_OK

DNS_KEY_COMPARE_FORMAT = "ZONE   {}\nDNSKEY {} {} {} {}\nDS     {} {} {} {}"
